### ISSUE TITLE
Add `CMD` to Dockerfile

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo-admin-docker#4]
At the moment the Dockerfile has no default CMD specified:

https://github.com/piccolo-orm/piccolo-admin-docker/blob/376f0ac0fd230036acd5e931703a275c1e774a71/Dockerfile

You have it in the Docker Compose file:

https://github.com/piccolo-orm/piccolo-admin-docker/blob/376f0ac0fd230036acd5e931703a275c1e774a71/docker-compose.yml#L4

But it should be in the Dockerfile instead, because someone might run the container without Docker Compose (e.g. via Kubernetes).

So it looks something like:

```
CMD ["python", "main.py"]
```

**Comment by sinisaos** [comment]
@dantownsend There was a [CMD command](https://github.com/piccolo-orm/piccolo-admin-docker/blob/13065169fc87b5766ce642303b93787f34737cda/Dockerfile) in the `Dockerfile`, but I guess I accidentally deleted it at some point. Sorry. I can add that or would you?

**Comment by dantownsend** [comment]
@sinisaos Yes, we should add it. But I think it should be this:

```
CMD ["python", "main.py"]
```

Because you specify `WORKDIR`, you can use `main.py` instead of specifying the full path.

I'll just create some issues for things we can add, and if you want to pick any of them up just assign yourself to it. I can do some too, just want to make sure we don't duplicate work.

**Comment by sinisaos** [comment]
@dantownsend I just managed to try `CMD ["python", "main.py"]`, but I get error from logs `python: cannot open file '/code/main.py': [Errno 2] No such file or directory`. If I run `CMD ["python", "app/main.py"]` everything works. I'm sorry if I'm doing something wrong, but I'm build a container with the command
```bash
docker build -t piccolo_admin .
```
and running the container with this command.
```bash
docker run --env-file .env -d --network=host --name admin_container piccolo_admin
```

**Comment by dantownsend** [comment]
@sinisaos Yes, you're right - I just rechecked the `Dockerfile`, and even though `WORKDIR` is `/code`, the app is added to `/code/app` so you need the `app/` prefix.

**Comment by sinisaos** [comment]
@dantownsend Great. I will make a PR to update the `Dockerfile` like this 

```dockerfile
FROM python:3.13-slim # solve issue 6

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

COPY ./config.yaml /code/config.yaml

VOLUME /data  # solve issue 8

RUN pip install --no-cache-dir -r /code/requirements.txt

COPY ./app /code/app

CMD ["python", "app/main.py"] # solve issue 4
```
which will close the 3 issues. 

For the rest of the issues I have to leave it up to you as I don't know anything about releasing to Docker Hub etc.
