### ISSUE TITLE
Use Python 3.13 as the base image

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo-admin-docker#6]
We may as well use Python 3.13 as the base image - as we're using Docker, we may as well just use the latest version.

https://github.com/piccolo-orm/piccolo-admin-docker/blob/376f0ac0fd230036acd5e931703a275c1e774a71/Dockerfile#L1

Eventually we might want to publish multiple image versions, but for now, lets just use the latest Python version.

**Comment by sinisaos** [comment]
@dantownsend I can add that if you want.

**Comment by dantownsend** [comment]
@sinisaos Cool, thanks!
